version: '3.8'

# ==========================================================
# VM 4: BALANCEADOR DE CARGA DE BASE DE DATOS (HAProxy DB)
# Capa 3 de la Arquitectura 2
# En GCP: Instancia e2-micro en Subred DB (IP 10.0.3.10)
# ==========================================================

services:
  haproxy-db:
    image: haproxy:2.8-alpine
    container_name: vm4_haproxy_db
    restart: always
    ports:
      - "5000:5000"   # Puerto de Escritura (Primario)
      - "5001:5001"   # Puerto de Lectura (Réplica)
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - red_cementerio

networks:
  red_cementerio:
    external: true
    name: red_cementerio_cluster
